// <auto-generated />
using System;
using EventApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251028183854_AddTagsAndEventTags")]
    partial class AddTagsAndEventTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventApi.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Visibility")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("StartDateTime");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Capacity = 10,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Location = "City Center",
                            StartDateTime = new DateTime(2025, 11, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Public Event 1",
                            Visibility = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Capacity = 15,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Location = "Park",
                            StartDateTime = new DateTime(2025, 11, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Public Event 2",
                            Visibility = true
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Capacity = 5,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Location = "Home",
                            StartDateTime = new DateTime(2025, 11, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Private Event",
                            Visibility = false
                        });
                });

            modelBuilder.Entity("EventApi.Models.EventTag", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("EventTags");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TagId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            EventId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TagId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            TagId = new Guid("77777777-7777-7777-7777-777777777777")
                        });
                });

            modelBuilder.Entity("EventApi.Models.Participant", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            JoinedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EventApi.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("LOWER(\"Name\") IS NOT NULL");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Art"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Business"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Music"
                        });
                });

            modelBuilder.Entity("EventApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user1@example.com",
                            PasswordHash = "$2a$12$yutgWM8YE0kHJ7t4EF4tz.qiDbwj3DlYSRKfL3T59RZ/0y4KPTidy"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user2@example.com",
                            PasswordHash = "$2a$12$23Tr52d2PMi5.o1tt4nld.tP0O5.LkpgN9jZMakBTp5vt9HiyPH/m"
                        });
                });

            modelBuilder.Entity("EventApi.Models.Event", b =>
                {
                    b.HasOne("EventApi.Models.User", "Creator")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("EventApi.Models.EventTag", b =>
                {
                    b.HasOne("EventApi.Models.Event", "Event")
                        .WithMany("EventTags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventApi.Models.Tag", "Tag")
                        .WithMany("EventTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("EventApi.Models.Participant", b =>
                {
                    b.HasOne("EventApi.Models.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventApi.Models.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventApi.Models.Event", b =>
                {
                    b.Navigation("EventTags");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("EventApi.Models.Tag", b =>
                {
                    b.Navigation("EventTags");
                });

            modelBuilder.Entity("EventApi.Models.User", b =>
                {
                    b.Navigation("CreatedEvents");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
